config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get 'home/index'
  get 'home/input'
  get 'home/test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def input
    @response = {}
    @content = params[:content]
    @ex = params[:extension]
    @name = SecureRandom.hex(2)
    @input = InputFile.new(@name,@content,@ex)
    @input.createFile
    @input.execute
    @response["response"] = @input.respond
    respond_to do |format|
      format.json { render json: @response}
    end
    FileDeleteJob.perform_later @name
  end

  def test
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_index.html.erb
<div class="col-md-8">
  <div class="row">
    <div >
      <h2>Compiler</h2>
      <div class="form-inline">

      <select class="form-control-sm col-md-3" name="language" id="sel">
        <option value="ruby">Ruby</option>
        <option value="javascript">JavaScript</option>
        <option value="python">Python3</option>
      </select>
       <h4 class="pull-right"><b class="font">Stats:</b><i class="icon-javascript" style="font-size:2em" id="js" ><%= @js.size %></i> || <i class="icon-python" style="font-size:2em" id="py" ><%= @py.size %></i> || <i class="icon-ruby" style="font-size:2em" id="rb" ><%= @rb.size %></i></h4><br/><br/>
    </div>

      <div class="col-md-12">
        <div id="text" class="padding-bottom"></div>
        <button type="button" name="execute" id="load" class="btn btn-primary">Execute</button>
        <button type="button" name="reset" id="reset" class="btn btn-danger">Reset</button>
        <button type="button" name="submit" class="btn btn-success" id="sub">Submit</button>
      </div>
    </div>
  </div>

    <div  id="para">
      <h2>Output</h2>
      <div id="result" class="padding-bottom"></div>
    </div>
<!-- accordion -->
<% if !@rb.empty? %>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Ruby Solutions
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <% @rb.each do |r| %>
          <li class="ruby" id="<%= r.id %>" ><b><%=r.user.username %></b>:<p><%= r.statement %><% if !(@a.include? r.id) %><button class="fork" id="<%= r.id %>" type="button" data-toggle="tooltip" title="Fork" value="ruby"><span class="glyphicon glyphicon-open" aria-hidden="true"></span></button><% else %><p>You already forked this</p><% end %></p></li>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% if !@js.empty? %>
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="headingTwo">
    <h4 class="panel-title">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Javascript solutions
      </a>
    </h4>
  </div>
  <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
    <div class="panel-body">
      <% @js.each do |j| %>
        <li class="javascript" id="<%= j.id %>"><b><%= j.user.username %></b>:<p><%= j.statement %><% if !(@a.include? j.id) %><button class="fork" id="<%= j.id %>" type="button" data-toggle="tooltip" title="Fork"value="javascript" ><span class="glyphicon glyphicon-open" aria-hidden="true"></span></button><% else %><p>You already forked this</p><% end %></p></li>
      <% end %>
    </div>
  </div>
</div>
<% end %>

<% if !@py.empty? %>
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="headingThree">
    <h4 class="panel-title">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Python Solutions
      </a>
    </h4>
  </div>
  <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
    <div class="panel-body">
      <% @py.each do |p| %>
      <li class="python" id="<%= p.id %>"><b><%= p.user.username %></b>:<p><%= p.statement %></p><% if !(@a.include? p.id) %><button class="fork" id="<%= p.id %>" type="button" data-toggle="tooltip" title="Fork" value="python"><span class="glyphicon glyphicon-open" aria-hidden="true"></span></button><% else %><p>You already forked this</p><% end %></p></li>
      <% end %>
    </div>
  </div>
</div>
<% end %>
</div>


<script type="text/javascript">
$(document).ready(function(){

  //this is fork code
  $("button.fork").on('click',function(){
    var type = $(this).val();
    var code = $("li#" + $(this).attr("id") + "." + type).find('p').text();
    switch (type) {
      case "javascript":
        $("#sel option[value="+type+"]").prop('selected','selected');
        editor.setOption("mode",type);
        editor.setOption("value",code);
        break;
      case "python":
        $("#sel option[value="+type+"]").prop('selected','selected');
        editor.setOption("mode",type);
        editor.setOption("value",code);
        break;
      default:
        $("#sel option[value="+type+"]").prop('selected','selected');
        editor.setOption("mode",type);
        editor.setOption("value",code);
        break;
    }//switch end
    var fork = {};
    fork["forks"] = {};
    fork["forks"]["user_id"] = "<%= current_user.id %>";
    fork["forks"]["answer_id"] = $(this).attr("id");
    $.ajax({
      url: "/forks",
      type: "post",
      data: fork,
      success: function(response){
        swal(
          'You forked this.'
        )
      }
    });
    $(this).hide();
  });


  //this is compiler code
  var flag = true;
  var lang = "ruby";
  var eName = "init";
  var web = "/answers/"
  var js = jcode = "//type code here";
  var pythoncon = pcode = "#type code here";
  var rubycon = rcode = "#type code here";
  var j = 1;
  var rid = 0;
  var jsid = 0;
  var pid = 0;
  check(lang);
  var editor = CodeMirror(document.getElementById('text'),{
    value: "#type code here",
    mode: "ruby",
    lineNumbers: true,
    keyMap: "sublime",
    theme: "monokai",
    tabSize: 2,
    indentUnit: 2,
    smartIndent: true,
    indentWithTabs: true,
    tabIndex: 2
  });
  var result = CodeMirror(document.getElementById('result'),{
    value: "Your result appears here",
    mode: "text",
    keyMap: "sublime",
    theme: "monokai",
    tabSize: 2,
    tabIndex: 2,
    readOnly: "nocursor"
  });

    $("#sel").on('change',function(){
      lang = this.value;
      check(lang);
    });

    function check(lang){
      $.ajax({
        url: "<%= home_check_cache_path %>",
        type: "get",
        data: {
          uid: "<%= current_user.id %>",
          aid: "<%= @assignment.id %>",
          language: lang
        },
        success: function(response){
          resp = response["response"]["statement"];
          if(resp == "default"){
          switch (lang) {
            case "python":
              editor.setOption("value",js);
              editor.setOption("value", pcode);
              result.setOption("value","Your result appears here");
              flag = true;
              break;
            case "javascript":
              editor.setOption("value", jcode);
              result.setOption("value","Your result appears here");
              flag = true;
              break;
            default:
              editor.setOption("value",js);
              editor.setOption("value",rcode);
              result.setOption("value","Your result appears here");
              flag = true;
              break;
          }
        }else{
          switch (lang) {
            case "python":
              editor.setOption("value",js);
              editor.setOption("value",resp);
              result.setOption("value","Your result appears here");
              pid = response["response"]["id"];
              web = "/answers/" + pid;
              flag = false;
              break;
            case "javascript":
              editor.setOption("value",resp);
              jsid = response["response"]["id"];
              result.setOption("value","Your result appears here");
              web = "/answers/" + jsid;
              flag = false;
              break;
            default:
              editor.setOption("value",js);
              editor.setOption("value",resp);
              result.setOption("value","Your result appears here");
              rid = response["response"]["id"];
              web = "/answers/" + rid;
              flag = false;
              break;
          }
        }
          editor.setOption("mode",lang);
        }
      });
    };


    $("#load").click(function(){
        var sent = editor.getValue();
        if(sent == js || sent == pythoncon || sent == rubycon){
          swal(
            'Ooops...!!!',
            "Looks like you din't type in any code.",
            'error'
          )
        }else{
          switch (lang) {
            case "python":
              pcode = sent;
              break;
            case "javascript":
              jcode = sent;
              break;
            default:
              rcode = sent;
              break;
          }
        $.ajax({
          url: "<%= home_input_path%>",
          type: "get",
          data: {
            content: sent,
            extension: lang
          },
          success: function(response){
            result.setOption("value", response["response"]);
          }
        });
      }
    });

    $("#sub").click(function(){
      var sent = editor.getValue();
      var out = result.getValue();
      var args = {};
      args["user_id"] = "<%= current_user.id %>";
      args["statement"] = sent;
      args["output"] = out;
      args["assignment_id"] = "<%= @assignment.id %>";
      args["language"] = lang;
      if(sent == js || sent == pythoncon || sent == rubycon || out == "Your result appears here"){
        swal(
          'Ooops...!!!',
          'You must execute before you submit your code.',
          'error'
        )
      }else{
        if(flag){
        $.ajax({
          url: "<%= answers_path %>",
          type: "post",
          data: {
            answer: args
          },
          success: function(response){
            swal(
              'Success',
              'Your code was submitted successfully.',
              'success'
            )
            $("#link").prop("hidden",false);
            switch(lang){
              case "javascript":
                $("#js").text(parseInt($("#js").text()) + 1);
                break;
              case "python":
                $("#py").text(parseInt($("#py").text()) + 1);
                break;
              default:
                $("#rb").text(parseInt($("#rb").text()) + 1);
                break;
            }
          }
        });
      }else{
        $.ajax({
          url: web,
          type: "patch",
          data: {
            answer: args
          },
          success: function(response){
            swal(
              'Success',
              'Your code was updated successfully.',
              'success'
            )
          }
        });
      }
    }
  });

  $("#reset").click(function(){
        swal({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, reset it!'
    }).then(function () {
      $("#sel").prop('selectedIndex',0);
      editor.setOption("value",js);
      editor.setOption("value",rubycon);
      result.setOption("value","Your result appears here");
      swal(
        'Reset!',
        'Your Work Has Been Reset.',
        'success'
      )
    },function(dismiss){
      if(dismiss === "cancel"){
        swal(
          'Cancelled'
        )
      }
    }
  )
  });

});//end of document
</script>

app/views/home/index.html.erb
<h2>APIs</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cc</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
crossorigin="anonymous"></script>

</head>

<body>

  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>